Project4/Models/Benh.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Project4.Models
{
    public class Benh
    {
        public int ID { get; set; }

        [DisplayName("Tên bệnh")]
        public string TenBenh { get; set; }
    }
}

Project4/Controllers/BenhsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project4.Models;

namespace Project4.Controllers
{
    public class BenhsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Benhs
        public ActionResult Index() 
        {
            return View(db.Benh.ToList());
        }

        // GET: Benhs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Benh benh = db.Benh.Find(id);
            if (benh == null)
            {
                return HttpNotFound(); 
            }
            return View(benh);
        }

        // GET: Benhs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Benhs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TenBenh")] Benh benh)
        {
            if (ModelState.IsValid)
            {
                db.Benh.Add(benh);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(benh);
        }

        // GET: Benhs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Benh benh = db.Benh.Find(id);
            if (benh == null)
            {
                return HttpNotFound();
            }
            return View(benh);
        }

        // POST: Benhs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TenBenh")] Benh benh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(benh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(benh);
        }

        // GET: Benhs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Benh benh = db.Benh.Find(id);
            if (benh == null)
            {
                return HttpNotFound();
            }
            return View(benh);
        }

        // POST: Benhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Benh benh = db.Benh.Find(id);
            db.Benh.Remove(benh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project4/Views/Benhs/Create.cshtml
@model Project4.Models.Benh

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Benh</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenBenh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenBenh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenBenh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/Benhs/Delete.cshtml
@model Project4.Models.Benh

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Benh</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenBenh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenBenh)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project4/Views/Benhs/Details.cshtml
@model Project4.Models.Benh

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Benh</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenBenh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenBenh)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project4/Views/Benhs/Edit.cshtml
@model Project4.Models.Benh

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Benh</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TenBenh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenBenh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenBenh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/Benhs/Index.cshtml
@model IEnumerable<Project4.Models.Benh>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}
 
<h2>Index quản lý bệnh của phạm nhân</h2> 
<br /> @Html.Partial("_BenhSearchBar")
<br /><p>@Html.ActionLink("Thêm mới", "Create")</p>
<br /> @Html.Partial("_BenhDataTable", Model.ToList())

Project4/Views/Benhs/_BenhDataTable.cshtml
@model IEnumerable<Project4.Models.Benh>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenBenh)
        </th>
        <th></th> 
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenBenh)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Project4/Views/Benhs/_BenhSearchBar.cshtml
@using (Html.BeginForm("Index", "Benhs", FormMethod.Get))
{
    <div class="container"> 
        <div class="row">
            <input type="text" class="form-control" placeholder="Tìm kiếm">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-search"></i>
            </button> 
        </div>
    </div>
}