Project4/Models/QuanNguc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Project4.Models
{
    public class QuanNguc
    {
        public Guid ID { get; set; }

        [DisplayName("Tên quản ngục")]
        public string TenQuanNguc { get; set; }

        [DisplayName("Ngày sinh")]
        public DateTime NgaySinh { get; set; }

        [DisplayName("Quê quán")]
        public string QueQuan { get; set; }

        [DisplayName("Giới tính")]
        public int GioiTinh { get; set; }

        [DisplayName("Khu")]
        public int KhuID { get; set; }

        [DisplayName("Năm công tác")]
        public int NamCongTac { get; set; }

        [DisplayName("Thời hạn công tác")]
        public int ThoiHanCongTac { get; set; }

        [DisplayName("Số thẻ căn cước")]
        public string CMND { get; set; }

        [DisplayName("Chức vụ")]
        public int ChucVu { get; set; } //enum

        [DisplayName("Quân hàm")]
        public int QuanHam { get; set; } //enum
    }
}

Project4/Controllers/QuanNgucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project4.Models;

namespace Project4.Controllers
{
    public class QuanNgucsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: QuanNgucs
        public ActionResult Index() 
        {
            var khuList = db.Khu.ToList();
            ViewBag.KhuQuanLi = new SelectList(khuList, "ID", "ID");
            return View(db.QuanNguc.ToList());
        }

        // GET: QuanNgucs/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuanNguc quanNguc = db.QuanNguc.Find(id);
            if (quanNguc == null)
            {
                return HttpNotFound();
            }
            return View(quanNguc);
        }

        // GET: QuanNgucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuanNgucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TenQuanNguc,NgaySinh,QueQuan,GioiTinh,KhuID,NamCongTac,ThoiHanCongTac,CMND,ChucVu,QuanHam")] QuanNguc quanNguc)
        {
            if (ModelState.IsValid)
            {
                quanNguc.ID = Guid.NewGuid();
                db.QuanNguc.Add(quanNguc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quanNguc);
        }

        // GET: QuanNgucs/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuanNguc quanNguc = db.QuanNguc.Find(id);
            if (quanNguc == null)
            {
                return HttpNotFound();
            }
            return View(quanNguc);
        }

        // POST: QuanNgucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TenQuanNguc,NgaySinh,QueQuan,GioiTinh,KhuID,NamCongTac,ThoiHanCongTac,CMND,ChucVu,QuanHam")] QuanNguc quanNguc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quanNguc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(quanNguc);
        }

        // GET: QuanNgucs/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuanNguc quanNguc = db.QuanNguc.Find(id);
            if (quanNguc == null)
            {
                return HttpNotFound();
            }
            return View(quanNguc);
        }

        // POST: QuanNgucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            QuanNguc quanNguc = db.QuanNguc.Find(id);
            db.QuanNguc.Remove(quanNguc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project4/Views/QuanNgucs/Create.cshtml
@model Project4.Models.QuanNguc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QuanNguc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenQuanNguc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenQuanNguc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenQuanNguc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QueQuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KhuID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KhuID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KhuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamCongTac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamCongTac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamCongTac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiHanCongTac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThoiHanCongTac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiHanCongTac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuanHam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuanHam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuanHam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/QuanNgucs/Delete.cshtml
@model Project4.Models.QuanNguc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuanNguc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenQuanNguc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenQuanNguc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QueQuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueQuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhuID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhuID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NamCongTac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamCongTac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiHanCongTac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiHanCongTac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChucVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChucVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuanHam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuanHam)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project4/Views/QuanNgucs/Details.cshtml
@model Project4.Models.QuanNguc

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Details</h2>

<div>
    <h4>QuanNguc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenQuanNguc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenQuanNguc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QueQuan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QueQuan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhuID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhuID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NamCongTac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamCongTac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiHanCongTac)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiHanCongTac)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChucVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChucVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuanHam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuanHam)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project4/Views/QuanNgucs/Edit.cshtml
@model Project4.Models.QuanNguc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QuanNguc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TenQuanNguc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenQuanNguc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenQuanNguc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QueQuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QueQuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QueQuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KhuID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KhuID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KhuID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamCongTac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamCongTac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamCongTac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiHanCongTac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThoiHanCongTac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiHanCongTac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChucVu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChucVu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuanHam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuanHam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuanHam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/QuanNgucs/Index.cshtml
@model IEnumerable<Project4.Models.QuanNguc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Index Quản ngục</h2>
@Html.Partial("_QuanNgucsSearchBar")
<br /><p>@Html.ActionLink("Thêm mới", "Create")</p>
@Html.Partial("_QuanNgucsDataTable", Model.ToList())

Project4/Views/QuanNgucs/_QuanNgucsDataTable.cshtml
@model IEnumerable<Project4.Models.QuanNguc>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenQuanNguc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QueQuan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KhuID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NamCongTac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThoiHanCongTac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChucVu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuanHam)
        </th>
        <th></th>
    </tr> 

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenQuanNguc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QueQuan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhuID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamCongTac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThoiHanCongTac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChucVu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuanHam)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Project4/Views/QuanNgucs/_QuanNgucsSearchBar.cshtml
@model IEnumerable<Project4.Models.QuanNguc>

@using (Html.BeginForm("Index", "QuanNgucs", FormMethod.Get))
{
    <div class="container">
        <div class="row"> 
            <div class="col-md-3">
                <input type="text" class="form-control" placeholder="Tìm kiếm">
            </div>
            <div class="col-md-2">
                @foreach (var item in Model)
                {
                    @Html.DropDownListFor(modelItem => item.KhuID, ViewBag.KhuQuanLi as SelectList
                        , "Khu quản lí", new { @class = "form-control" })
                }
            </div>
            <div class="col-md-1">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
}