Project4/Models/ThamGui.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Project4.Models
{
    public class ThamGui
    {
        public int ID { get; set; }

        [DisplayName("Phạm nhân")]
        public Guid PhamNhanID { get; set; }

        [DisplayName("Quản ngục coi")]
        public Guid QuanNgucID { get; set; }

        [DisplayName("Kế hoạch thăm gửi")]
        public int KeHoachThamGui { get; set; } //enum

        [DisplayName("Ngày thăm")]
        public DateTime NgayThamGui { get; set; }

        [DisplayName("Thông tin người thăm hỏi")]
        public string ThongTinNguoiThamHoi { get; set; }

        [DisplayName("Số lần thăm hỏi")]
        public int SoLanThamHoi { get; set; }

    }
}

Project4/Controllers/ThamGuisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project4.Models;

namespace Project4.Controllers
{
    public class ThamGuisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ThamGuis
        public ActionResult Index()
        {
            return View(db.ThamGui.ToList());
        }

        // GET: ThamGuis/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThamGui thamGui = db.ThamGui.Find(id);
            if (thamGui == null)
            {
                return HttpNotFound();
            }
            return View(thamGui);
        }

        // GET: ThamGuis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThamGuis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PhamNhanID,QuanNgucID,KeHoachThamGui,NgayThamGui,ThongTinNguoiThamHoi,SoLanThamHoi")] ThamGui thamGui)
        {
            if (ModelState.IsValid)
            {
                db.ThamGui.Add(thamGui);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(thamGui);
        }

        // GET: ThamGuis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThamGui thamGui = db.ThamGui.Find(id);
            if (thamGui == null)
            {
                return HttpNotFound();
            }
            return View(thamGui);
        }

        // POST: ThamGuis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PhamNhanID,QuanNgucID,KeHoachThamGui,NgayThamGui,ThongTinNguoiThamHoi,SoLanThamHoi")] ThamGui thamGui)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thamGui).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thamGui);
        }

        // GET: ThamGuis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThamGui thamGui = db.ThamGui.Find(id);
            if (thamGui == null)
            {
                return HttpNotFound();
            }
            return View(thamGui);
        }

        // POST: ThamGuis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ThamGui thamGui = db.ThamGui.Find(id);
            db.ThamGui.Remove(thamGui);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project4/Views/ThamGuis/Create.cshtml
@model Project4.Models.ThamGui

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ThamGui</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PhamNhanID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhamNhanID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhamNhanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuanNgucID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuanNgucID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuanNgucID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KeHoachThamGui, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KeHoachThamGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KeHoachThamGui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayThamGui, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayThamGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayThamGui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongTinNguoiThamHoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTinNguoiThamHoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTinNguoiThamHoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLanThamHoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLanThamHoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLanThamHoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/ThamGuis/Delete.cshtml
@model Project4.Models.ThamGui

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ThamGui</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhamNhanID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhamNhanID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuanNgucID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuanNgucID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KeHoachThamGui)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KeHoachThamGui)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayThamGui)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayThamGui)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinNguoiThamHoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinNguoiThamHoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLanThamHoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLanThamHoi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project4/Views/ThamGuis/Details.cshtml
@model Project4.Models.ThamGui

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ThamGui</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PhamNhanID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhamNhanID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuanNgucID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuanNgucID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KeHoachThamGui)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KeHoachThamGui)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayThamGui)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayThamGui)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinNguoiThamHoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinNguoiThamHoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLanThamHoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLanThamHoi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project4/Views/ThamGuis/Edit.cshtml
@model Project4.Models.ThamGui

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ThamGui</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PhamNhanID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhamNhanID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhamNhanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuanNgucID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuanNgucID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuanNgucID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KeHoachThamGui, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KeHoachThamGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KeHoachThamGui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayThamGui, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayThamGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayThamGui, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongTinNguoiThamHoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTinNguoiThamHoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTinNguoiThamHoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLanThamHoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLanThamHoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLanThamHoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/ThamGuis/Index.cshtml
@model IEnumerable<Project4.Models.ThamGui>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Index Thăm gửi</h2>
<br /> @Html.Partial("_ThamGuisSearchBar")
<br /><p>@Html.ActionLink("Thêm mới", "Create")</p>
<br /> @Html.Partial("_ThamGuisDataTable")

Project4/Views/ThamGuis/_ThamGuisDataTable.cshtml
@model IEnumerable<Project4.Models.ThamGui>

<table class="table"> 
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PhamNhanID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuanNgucID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KeHoachThamGui)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgayThamGui)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThongTinNguoiThamHoi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLanThamHoi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PhamNhanID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuanNgucID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KeHoachThamGui)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayThamGui)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThongTinNguoiThamHoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLanThamHoi)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Project4/Views/ThamGuis/_ThamGuisSearchBar.cshtml
@model IEnumerable<Project4.Models.ThamGui>

@using (Html.BeginForm("Index", "ThamGuis", FormMethod.Get))
{
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <input type="text" class="form-control" placeholder="Tìm kiếm">
            </div>
            <div class="col-md-2">
                @foreach (var item in Model)
                {
                    @Html.DropDownListFor(modelItem => item.ID, ViewBag.Khu as SelectList
                        , "Khu", new { @class = "form-control" })
                } 
            </div>
            <div class="col-md-2">
                @foreach (var item in Model) 
                {
                    @Html.DropDownListFor(modelItem => item.ID, ViewBag.Phong as SelectList
                        , "Phòng giam", new { @class = "form-control" })
                }
            </div>
            <div class="col-md-1">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
}