Project4/Models/CheDoNghiPhepCuaQuanNguc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Project4.Models
{
    public class CheDoNghiPhepCuaQuanNguc
    {
        public int ID { get; set; } 

        [DisplayName("Quản ngục ID")]
        public Guid QuanNgucID { get; set; }

        [DisplayName("Số ngày nghỉ")]
        public int SoNgayNghi { get; set; }

        [DisplayName("Lý do nghỉ")]
        public string LyDoNghi { get; set; }
    }
}

Project4/Controllers/CheDoNghiPhepCuaQuanNgucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project4.Models;

namespace Project4.Controllers 
{
    public class CheDoNghiPhepCuaQuanNgucsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CheDoNghiPhepCuaQuanNgucs
        public ActionResult Index()
        {
            var khuList = db.Khu.ToList();
            ViewBag.KhuQuanLi = new SelectList(khuList, "ID", "ID"); 
            return View(db.CheDoNghiPhepCuaQuanNguc.ToList());
        }

        // GET: CheDoNghiPhepCuaQuanNgucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheDoNghiPhepCuaQuanNguc cheDoNghiPhepCuaQuanNguc = db.CheDoNghiPhepCuaQuanNguc.Find(id);
            if (cheDoNghiPhepCuaQuanNguc == null)
            {
                return HttpNotFound();
            }
            return View(cheDoNghiPhepCuaQuanNguc);
        }

        // GET: CheDoNghiPhepCuaQuanNgucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheDoNghiPhepCuaQuanNgucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,QuanNgucID,SoNgayNghi,LyDoNghi")] CheDoNghiPhepCuaQuanNguc cheDoNghiPhepCuaQuanNguc)
        {
            if (ModelState.IsValid)
            {
                db.CheDoNghiPhepCuaQuanNguc.Add(cheDoNghiPhepCuaQuanNguc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cheDoNghiPhepCuaQuanNguc);
        }

        // GET: CheDoNghiPhepCuaQuanNgucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheDoNghiPhepCuaQuanNguc cheDoNghiPhepCuaQuanNguc = db.CheDoNghiPhepCuaQuanNguc.Find(id);
            if (cheDoNghiPhepCuaQuanNguc == null)
            {
                return HttpNotFound();
            }
            return View(cheDoNghiPhepCuaQuanNguc);
        }

        // POST: CheDoNghiPhepCuaQuanNgucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,QuanNgucID,SoNgayNghi,LyDoNghi")] CheDoNghiPhepCuaQuanNguc cheDoNghiPhepCuaQuanNguc)
        {
            if (ModelState.IsValid) 
            {
                db.Entry(cheDoNghiPhepCuaQuanNguc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cheDoNghiPhepCuaQuanNguc);
        }

        // GET: CheDoNghiPhepCuaQuanNgucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheDoNghiPhepCuaQuanNguc cheDoNghiPhepCuaQuanNguc = db.CheDoNghiPhepCuaQuanNguc.Find(id);
            if (cheDoNghiPhepCuaQuanNguc == null)
            {
                return HttpNotFound();
            }
            return View(cheDoNghiPhepCuaQuanNguc);
        }

        // POST: CheDoNghiPhepCuaQuanNgucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CheDoNghiPhepCuaQuanNguc cheDoNghiPhepCuaQuanNguc = db.CheDoNghiPhepCuaQuanNguc.Find(id);
            db.CheDoNghiPhepCuaQuanNguc.Remove(cheDoNghiPhepCuaQuanNguc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project4/Views/CheDoNghiPhepCuaQuanNgucs/Create.cshtml
@model Project4.Models.CheDoNghiPhepCuaQuanNguc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheDoNghiPhepCuaQuanNguc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.QuanNgucID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuanNgucID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuanNgucID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoNgayNghi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoNgayNghi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoNgayNghi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LyDoNghi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LyDoNghi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LyDoNghi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/CheDoNghiPhepCuaQuanNgucs/Delete.cshtml
@model Project4.Models.CheDoNghiPhepCuaQuanNguc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CheDoNghiPhepCuaQuanNguc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuanNgucID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuanNgucID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoNgayNghi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoNgayNghi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LyDoNghi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LyDoNghi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project4/Views/CheDoNghiPhepCuaQuanNgucs/Details.cshtml
@model Project4.Models.CheDoNghiPhepCuaQuanNguc

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CheDoNghiPhepCuaQuanNguc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuanNgucID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuanNgucID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoNgayNghi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoNgayNghi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LyDoNghi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LyDoNghi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project4/Views/CheDoNghiPhepCuaQuanNgucs/Edit.cshtml
@model Project4.Models.CheDoNghiPhepCuaQuanNguc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheDoNghiPhepCuaQuanNguc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.QuanNgucID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuanNgucID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuanNgucID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoNgayNghi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoNgayNghi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoNgayNghi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LyDoNghi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LyDoNghi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LyDoNghi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project4/Views/CheDoNghiPhepCuaQuanNgucs/Index.cshtml
@model IEnumerable<Project4.Models.CheDoNghiPhepCuaQuanNguc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Index chế độ nghỉ phép của quản ngục</h2>
<br /> @Html.Partial("_NghiPhepQuanNgucsSearchBar")
<br /><p>@Html.ActionLink("Thêm mới", "Create")</p>
<br /> @Html.Partial("_NghiPhepQuanNgucsDataTable", Model.ToList())

Project4/Views/CheDoNghiPhepCuaQuanNgucs/_NghiPhepQuanNgucsDataTable.cshtml
@model IEnumerable<Project4.Models.CheDoNghiPhepCuaQuanNguc>
<table class="table">
    <tr>   
        <th>
            @Html.DisplayNameFor(model => model.QuanNgucID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoNgayNghi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LyDoNghi)
        </th>
        <th></th>
    </tr> 

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuanNgucID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoNgayNghi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LyDoNghi)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Project4/Views/CheDoNghiPhepCuaQuanNgucs/_NghiPhepQuanNgucsSearchBar.cshtml
@model IEnumerable<Project4.Models.CheDoNghiPhepCuaQuanNguc>

@using (Html.BeginForm("Index", "CheDoNghiPhepCuaQuanNgucs", FormMethod.Get))
{
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <input type="text" class="form-control" placeholder="Tìm kiếm">
            </div>
            <div class="col-md-2">
                @foreach (var item in Model)
                {
                    @Html.DropDownListFor(modelItem => item.ID, ViewBag.Khu as SelectList
                        , "Khu", new { @class = "form-control" })
                }
            </div>
            <div class="col-md-1">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
            <div class="col-md-6">
            </div>
        </div>
    </div>
}